### ISSUE TITLE
Featured posts, only seems to feature two but I'm unsure why.

### ISSUE THREAD

**Issue by RussellTaylor83** [zulfnore/fourteen-extended#4]
Hello,

Thank you for all your efforts in this plugin. I've added it as I would like to reorder my featured posts, and make the featured images span the full width :+1: 

Taking the latest from here, if I enabled the plugin only two of my five featured posts become featured. I am using tags to mark them as featured. Also the 100% width option for featured tags seemed to work momentarily and then stopped.

I will try to help debug this and post anything I find, although I'm quite slow with Wordpress and PHP. I'm wondering if it's a conflict with another setting I have made in the plugin. I have a vanilla WP install with no other plugins or style changes, all settings updated through Customise Theme.

All the best, thanks again

Russ

**Comment by zulfnore** [comment]
This issue has been resolved in the latest update - please test and advise.

**Comment by tarius68** [comment]
It is working now! Great job! Thank you very much.
